"""actualizacion comment and rate

Revision ID: 2008b9a14636
Revises: 2fce2e24f1c1
Create Date: 2026-05-09 23:01:58.821878

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2008b9a14636'
down_revision = '2fce2e24f1c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rates', schema=None) as batch_op:
        batch_op.alter_column('id_rate',
               existing_type=mysql.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.create_unique_constraint(None, ['id_rate'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rates', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('id_rate',
               existing_type=mysql.INTEGER(),
               nullable=False,
               autoincrement=True)

    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('id_comment'), ['id_comment'], unique=True)
        batch_op.drop_column('date_of_update')

    # ### end Alembic commands ###
