"""mejora del modelo rate agregandole un id propio

Revision ID: 2fce2e24f1c1
Revises: 72761c6db288
Create Date: 2026-04-21 10:41:01.396916

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2fce2e24f1c1'
down_revision = '72761c6db288'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_rate', sa.Integer(), autoincrement=True, nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rates', schema=None) as batch_op:
        batch_op.drop_column('id_rate')

    # ### end Alembic commands ###
