"""eliminacion de la clave foranea comentarios por fallo de diseño

Revision ID: 5dbd096f852a
Revises: 8ddfb0ab4c83
Create Date: 2026-04-14 11:11:06.791833

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5dbd096f852a'
down_revision = '8ddfb0ab4c83'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_videogame', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'videoGame', ['id_videogame'], ['id_game_api'])

    with op.batch_alter_table('videoGame', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('videoGame_ibfk_1'), type_='foreignkey')
        batch_op.drop_column('id_comment')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('videoGame', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_comment', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('videoGame_ibfk_1'), 'comments', ['id_comment'], ['id_comment'])

    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('id_videogame')

    # ### end Alembic commands ###
