"""act_ fechas nulas

Revision ID: 8ddfb0ab4c83
Revises: 8e903b1dd287
Create Date: 2026-04-08 09:39:05.787042

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ddfb0ab4c83'
down_revision = '8e903b1dd287'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('videoGame', schema=None) as batch_op:
        batch_op.alter_column('date_release',
               existing_type=sa.DATE(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('videoGame', schema=None) as batch_op:
        batch_op.alter_column('date_release',
               existing_type=sa.DATE(),
               nullable=False)

    # ### end Alembic commands ###
