"""estructura inicial

Revision ID: 8e903b1dd287
Revises: 
Create Date: 2026-04-07 13:41:52.129017

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e903b1dd287'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id_user', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('date_of_registration', sa.Date(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id_user'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('password')
    )
    op.create_table('comments',
    sa.Column('id_comment', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('date_of_comment', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['id_user'], ['users.id_user'], ),
    sa.PrimaryKeyConstraint('id_comment', 'id_user'),
    sa.UniqueConstraint('id_comment')
    )
    op.create_table('videoGame',
    sa.Column('id_game_api', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('date_release', sa.Date(), nullable=False),
    sa.Column('platforms', sa.String(length=200), nullable=True),
    sa.Column('development_company', sa.String(length=100), nullable=False),
    sa.Column('id_comment', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_comment'], ['comments.id_comment'], ),
    sa.PrimaryKeyConstraint('id_game_api')
    )
    op.create_table('favorites',
    sa.Column('fav_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('id_game_api', sa.Integer(), nullable=False),
    sa.Column('date_added', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['id_game_api'], ['videoGame.id_game_api'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id_user'], ),
    sa.PrimaryKeyConstraint('fav_id', 'user_id', 'id_game_api')
    )
    op.create_table('rates',
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('id_game_api', sa.Integer(), nullable=False),
    sa.Column('date_rate', sa.Date(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['id_game_api'], ['videoGame.id_game_api'], ),
    sa.ForeignKeyConstraint(['id_user'], ['users.id_user'], ),
    sa.PrimaryKeyConstraint('id_user', 'id_game_api')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rates')
    op.drop_table('favorites')
    op.drop_table('videoGame')
    op.drop_table('comments')
    op.drop_table('users')
    # ### end Alembic commands ###
