"""correccion de eliminacion en cascada

Revision ID: f7f639db60e5
Revises: 5dbd096f852a
Create Date: 2026-04-14 11:40:20.123054

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7f639db60e5'
down_revision = '5dbd096f852a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('comments_ibfk_2'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('comments_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['id_user'], ['id_user'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'videoGame', ['id_videogame'], ['id_game_api'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('comments_ibfk_1'), 'users', ['id_user'], ['id_user'])
        batch_op.create_foreign_key(batch_op.f('comments_ibfk_2'), 'videoGame', ['id_videogame'], ['id_game_api'])

    # ### end Alembic commands ###
